# Generated by Django 3.2.16 on 2022-12-14 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20221205_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='disabled_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
        migrations.AlterField(
            model_name='package',
            name='enabled_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
    ]
