# Generated by Django 3.2.16 on 2022-12-18 11:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20221214_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='content_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='extra_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
        migrations.AddField(
            model_name='package',
            name='prototype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='source_file',
            field=models.BooleanField(default=False),
        ),
    ]
