# Generated by Django 3.2.16 on 2022-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_remove_package_extra_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='disabled_services',
        ),
        migrations.RemoveField(
            model_name='package',
            name='enabled_services',
        ),
        migrations.AddField(
            model_name='package',
            name='consulatation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='deployment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='integration',
            field=models.BooleanField(default=False),
        ),
    ]
