# Generated by Django 3.2.16 on 2022-11-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.RemoveField(
            model_name='account',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
    ]
