# Generated by Django 3.2.16 on 2022-11-28 06:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='certifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='educations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8),
        ),
    ]
