# Generated by Django 3.2.16 on 2022-12-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20221214_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
