# Generated by Django 3.2.16 on 2022-12-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20221217_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='tagline',
        ),
    ]
