# Generated by Django 3.2.16 on 2022-12-18 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_remove_profiles_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
