# Generated by Django 3.2.16 on 2022-12-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('gig', '0003_auto_20221205_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='gig_tags', to='tag.Tag'),
        ),
    ]
