# Generated by Django 3.2.16 on 2022-12-05 01:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0004_alter_gig_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='expertises',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
        migrations.AlterField(
            model_name='gig',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
        migrations.AlterField(
            model_name='gig',
            name='specializations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
    ]
