# Generated by Django 3.2.16 on 2022-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('image', '0001_initial'),
        ('gig', '0005_auto_20221205_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='gig_images', to='image.Image'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='gig_tags', to='tag.Tag'),
        ),
    ]
