# Generated by Django 3.2.16 on 2022-12-12 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig', '0008_auto_20221212_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='downvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='gig_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=None, related_name='gig_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
