# Generated by Django 3.2.16 on 2022-12-17 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0010_gig_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='faq',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=20),
        ),
    ]
