# Generated by Django 3.2.16 on 2022-12-18 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0011_alter_gig_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='tags',
        ),
        migrations.AddField(
            model_name='gig',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=8),
        ),
    ]
