# Generated by Django 3.2.16 on 2022-12-18 11:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0012_auto_20221218_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='extra_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8),
        ),
    ]
