# Generated by Django 3.2.16 on 2022-12-18 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0013_gig_extra_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=8),
        ),
        migrations.AddField(
            model_name='gig',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=8),
        ),
    ]
