# Generated by Django 3.2.16 on 2022-12-18 12:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0014_auto_20221218_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=8),
        ),
    ]
