# Generated by Django 3.2.16 on 2022-12-19 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0015_gig_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=8),
        ),
    ]
