# Generated by Django 3.2.16 on 2022-12-20 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0016_alter_gig_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
    ]
