# Generated by Django 3.2.16 on 2022-12-24 05:23

import advertisement.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=150)),
                ('url', models.URLField(max_length=300)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=advertisement.models.RenameAndRelocateImage('images/'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
