# Generated by Django 3.2.16 on 2022-12-12 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#d5b60a', max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid color format. RGB hex color format needed.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
