# Generated by Django 3.2.16 on 2023-04-15 17:48

from django.db import migrations, models
import event.models
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('ticket_title', models.CharField(blank=True, default=None, max_length=100)),
                ('ticket_description', tinymce.models.HTMLField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=event.models.RenameAndRelocateImage('images/'))),
                ('ticket_availability', models.IntegerField(default=0)),
                ('regular_price', models.IntegerField(default=0)),
                ('premium_price', models.IntegerField(default=0)),
                ('regular_features', models.TextField()),
                ('premium_features', models.TextField()),
                ('location', models.CharField(blank=True, default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
