# Generated by Django 3.2.16 on 2023-01-15 05:45

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('image', '0002_alter_image_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(15)])),
                ('description', models.TextField()),
                ('start_at', models.DateTimeField()),
                ('finish_at', models.DateTimeField()),
                ('location_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('location_link', models.URLField(blank=True, max_length=300, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=20)),
                ('faq', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=20)),
                ('services', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8)),
                ('rules', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=8)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), default=list, size=8)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=15)),
                ('type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('limited', 'Limited')], default='free', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('cover', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='image.image')),
                ('downvotes', models.ManyToManyField(blank=True, default=None, related_name='event_downvotes', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='image.Image')),
                ('upvotes', models.ManyToManyField(blank=True, default=None, related_name='event_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
