# Generated by Django 3.2.16 on 2023-04-16 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20230417_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time_from',
            field=models.TimeField(default=datetime.time(15, 27, 25, 125763)),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time_to',
            field=models.TimeField(default=datetime.time(15, 27, 25, 125763)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(default=datetime.date(2023, 4, 16)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(default=datetime.date(2023, 4, 16)),
        ),
    ]
