# Generated by Django 3.2.16 on 2023-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20230417_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time_to',
            field=models.TimeField(),
        ),
    ]
