# Generated by Django 3.2.16 on 2023-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_ticket_description_event_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_form_iframe',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
