# Generated by Django 3.2.16 on 2023-04-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_google_form_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_form_iframe',
            field=models.URLField(max_length=500),
        ),
    ]
