# Generated by Django 3.2.16 on 2023-04-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_google_form_iframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='google_form_iframe',
            new_name='google_form_iframe_url',
        ),
    ]
