# Generated by Django 3.2.16 on 2022-12-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gig',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
