# Generated by Django 3.2.16 on 2023-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20221225_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('dropped', 'Dropped')], default='pending', max_length=10),
        ),
    ]
